# Clippy configuration for strict linting
# This file configures clippy to be very strict about code quality

# Enable all lints
all-targets = true

# Deny warnings (treat warnings as errors)
deny-warnings = true

# Specific lint configurations
warn-on-all-wildcard-imports = true
warn-on-all-wildcard-imports = true

# Performance lints
warn-performance = true

# Style lints
warn-style = true

# Correctness lints
warn-correctness = true

# Complexity lints
warn-complexity = true

# Pedantic lints
warn-pedantic = true

# Nursery lints (experimental)
warn-nursery = true

# Cargo lints
warn-cargo = true
