# Rust linting configuration
[package]
name = "daily-update-service"
version = "0.1.0"
edition = "2021"

# Clippy configuration
[tool.clippy]
all-targets = true
warn-on-all-wildcard-imports = true
warn-on-all-wildcard-imports = true
deny-warnings = true

# Rustfmt configuration
[tool.rustfmt]
max_width = 100
tab_spaces = 2
newline_style = "Unix"
use_small_heuristics = "Max"
